### ISSUE TITLE
Missplacement of rest.whole

### ISSUE THREAD

**Issue by martha-thomae** [HISPAMUS/muret#14] opened 2019-06-17 15:02 UTC
A rest which was correctly labeled as rest.whole is placed in the staff in a position that would correspond to a rest.half. (This was the place where the algorithm positioned the rest, I didn't move it.)

![Catalogued as rest whole but looks like rest half](https://user-images.githubusercontent.com/13948831/59614725-98803c80-9121-11e9-8353-05c9d600b969.png)

**Comment by davidrizo** [comment] 2019-06-17 16:30
This is the same as 
Duplicate of #7.
Currently, the provided example is correctly tagged in L4

**Closed by davidrizo** 2019-06-17 16:30 UTC

**Comment by martha-thomae** [comment] 2019-06-17 16:52
The provided example is tagged as S3 in the screenshot (I manually corrected it to L4 in MuRET).

**Comment by martha-thomae** [comment] 2019-06-17 16:53
Is it the same issue? The screenshot represents how MuRET positioned the rest when I made the bounding box. It is not the result of a movement up or down.
